name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - master

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yaml
    with:
      dir: backend
  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      dockerhub_repo: gagal1818/pomo-backend
      default_branch: master
      file: ./backend/ci/Dockerfile
      dir: ./backend
    secrets:
      dockerhub_username: ${{ secrets.DO_HUB_USER }}
      dockerhub_password: ${{ secrets.DO_HUB_PW }}
      gh_token: ${{ secrets.GH_TOKEN }}   