name: Reusable Lint, Build, and Push

on:
  workflow_call:
    inputs:
      dockerhub_repo:
        required: true
        type: string
      default_branch:
        required: false
        type: string
        default: master
      dir:
        required: false
        type: string
        default: master 
      file:
        required: false
        type: string
        default: master 

    secrets:
      gh_token:
        required: true
      dockerhub_username:
        required: true
      dockerhub_password:
        required: true

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ inputs.default_branch }}
          GITHUB_TOKEN: ${{ secrets.gh_token }}

  docker:
    runs-on: ubuntu-latest
    needs: run-lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}

      - name: Extract commit hash
        id: vars
        run: echo "TAG=${GITHUB_SHA::6}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.dir }}
          file: ${{ inputs.file }}
          push: true
          tags: ${{ inputs.dockerhub_repo }}:${{ env.TAG }}
