name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - master

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yaml
    with:
      working-directory: frontend

  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      dockerhub_repo: gagal1818/pomo-frontend
      default_branch: master
    secrets:
      dockerhub_username: ${{ secrets.DO_HUB_USER }}
      dockerhub_password: ${{ secrets.DO_HUB_PW }}
      gh_token: ${{ secrets.GH_TOKEN }}    